apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker-phpeste
spec:
  host: phpeste-service.default.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 2
      consecutiveGatewayErrors: 1
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 100