apiVersion: v1
kind: Service
metadata:
  name: phpeste-service
spec:
  selector:
    app: phpeste
  type: ClusterIP
  ports:
  - name: phpeste-service
    port: 80
    targetPort: 3000
    protocol: TCP